server:
  port: 8080
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/websoketTest
    username: postgres
    password: 0000
logging:
  level:
    org:
      springframework:
        web:
          client: DEBUG
      hibernate:
        type: TRACE